<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Form fields
 */
$GLOBALS['TL_LANG']['FFL']['metamodels_notelist']   	 				= array('Merkliste, MetaModels', 'Ein individuelles Feld zum Einfügen einer Bereichsüberschrift.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_form_field']['template_legend']  				= 'Template-Einstellungen';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['metamodels_notelist_formTpl']		= array('Ausgabe-Template','Wählen Sie hier das Ausgabe-Template.');
$GLOBALS['TL_LANG']['tl_form_field']['metamodels_notelist_mailTpl']		= array('Mail-Template','Wählen Sie hier das Mail-Template.');
$GLOBALS['TL_LANG']['tl_form_field']['metamodels_notelist_metamodel']	= array('MetaModel auswählen','Wählen Sie hier das MetaModel aus.');
$GLOBALS['TL_LANG']['tl_form_field']['metamodels_notelist_visibles']	= array('Sichbare Felder','Wählen Sie hier die sichtbaren Felder aus.');


?>